config/routes.rb
Rails.application.routes.draw do
  resources :sandwiches
  devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  root "sandwiches#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sandwich.rb
class Sandwich < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.name = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def fly
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
  before_action :set_sandwich, only: %i[ show edit update destroy ]

  # GET /sandwiches or /sandwiches.json
  def index
    @sandwiches = Sandwich.all
  end

  # GET /sandwiches/1 or /sandwiches/1.json
  def show
  end

  # GET /sandwiches/new
  def new
    @sandwich = Sandwich.new
  end

  # GET /sandwiches/1/edit
  def edit
  end

  # POST /sandwiches or /sandwiches.json
  def create
    @sandwich = Sandwich.new(sandwich_params)

    respond_to do |format|
      if @sandwich.save
        format.html { redirect_to sandwich_url(@sandwich), notice: "Sandwich was successfully created." }
        format.json { render :show, status: :created, location: @sandwich }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sandwiches/1 or /sandwiches/1.json
  def update
    respond_to do |format|
      if @sandwich.update(sandwich_params)
        format.html { redirect_to sandwich_url(@sandwich), notice: "Sandwich was successfully updated." }
        format.json { render :show, status: :ok, location: @sandwich }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sandwiches/1 or /sandwiches/1.json
  def destroy
    @sandwich.destroy

    respond_to do |format|
      format.html { redirect_to sandwiches_url, notice: "Sandwich was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sandwich
      @sandwich = Sandwich.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sandwich_params
      params.require(:sandwich).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/views/layouts/_nav.erb
<ul>
<% if user_signed_in? %>
<li><%= link_to "Edit your account", edit_user_registration_path %></li>
<li><%= button_to "Sign out", destroy_user_session_path, method: :delete %></li>
<% else %>
<li><%= link_to "Sign in", new_user_session_path %></li>
<li><%= link_to "Sign up", new_user_registration_path %></li>
<%end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlyioOauthSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render 'layouts/nav'%>

    <%= yield %>
  </body>
</html>

app/views/sandwiches/_form.html.erb
<%= form_with(model: sandwich) do |form| %>
  <% if sandwich.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sandwich.errors.count, "error") %> prohibited this sandwich from being saved:</h2>

      <ul>
        <% sandwich.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sandwiches/_sandwich.html.erb
<div id="<%= dom_id sandwich %>">
  <p>
    <strong>Name:</strong>
    <%= sandwich.name %>
  </p>

</div>

app/views/sandwiches/edit.html.erb
<h1>Editing sandwich</h1>

<%= render "form", sandwich: @sandwich %>

<br>

<div>
  <%= link_to "Show this sandwich", @sandwich %> |
  <%= link_to "Back to sandwiches", sandwiches_path %>
</div>

app/views/sandwiches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sandwiches</h1>

<div id="sandwiches">
  <% @sandwiches.each do |sandwich| %>
    <%= render sandwich %>
    <p>
      <%= link_to "Show this sandwich", sandwich %>
    </p>
  <% end %>
</div>

<%= link_to "New sandwich", new_sandwich_path %>

app/views/sandwiches/new.html.erb
<h1>New sandwich</h1>

<%= render "form", sandwich: @sandwich %>

<br>

<div>
  <%= link_to "Back to sandwiches", sandwiches_path %>
</div>

app/views/sandwiches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sandwich %>

<div>
  <%= link_to "Edit this sandwich", edit_sandwich_path(@sandwich) %> |
  <%= link_to "Back to sandwiches", sandwiches_path %>

  <%= button_to "Destroy this sandwich", @sandwich, method: :delete %>
</div>